if (typeof cardsData === 'undefined'){
    var cardsData = [
        {
            projectName: 'PDF-Describer',
            description: 'Python app that takes data from CSV file and inserts it to PDF file',
            details: `PDF-Describer is a simple Python app, created to automatize some tasks that I often performed in one of my previous jobs as a Process Engineer.
            <br><br>
            It takes data from CSV file generated by the IPOsystem (Intelligent Production Organizing system) and inserts it to technical documentation in PDF file in a certain way.
            <br><br>
            The app saves from 20 minutes up to even 2 hours per project, depending on the project's size and complexity ('project' should be understood as a construction intended to be produced). I estimate that the <u>app saves cumulatively about 50-55 hours per month on average</u> in the department. It was successfully implemented and is still used.
            <br><br>
            PDF-Describer combines Python code (for GUI and functionality) with some VBA macros that are automatically ran during app's execution.
            <br>
            Because the application has been sold, the code cannot be shared.`,
            status: 'closed',
            tech: 'Python, VBA',
            github: '',
            website: '',
            img: ['https://raw.githubusercontent.com/arekjg/PDF-Describer/master/screens/gui.png?token=GHSAT0AAAAAACEOE46WUPXWVWDYI7NRHCBYZIRXYHA']
        },
        {
            projectName: 'TechCreator',
            description: 'WPF app that simplifies creating production schemas for IPOsystem (Intelligent Prodcution Organizing system)',
            details: 'long description of an application',
            status: 'closed',
            tech: 'C#, WPF',
            github: '',
            website: ''
        },
        {
            projectName: 'Battleship',
            description: 'Battleship game written in JS, final project in the CS50\'s Introduction to Computer Science course',
            details: 'long description of an application',
            status: 'closed',
            tech: 'HTML, CSS, JavaScript',
            github: 'https://github.com/arekjg/battleship_js',
            website: ''
        },
        {
            projectName: 'ActivityManager',
            description: 'WPF app for adding, deleting and viewing data from SQL database.',
            details: 'long description of an application',
            status: 'in development',
            tech: 'C#, WPF, MS SQL, EFCore',
            github: '',
            website: ''
        },
        {
            projectName: 'GitHubStats',
            description: 'Console .NET app that communicates with GitHub API and provides user statistics to be included in "readme" file',
            details: 'long description of an application',
            status: 'in development',
            tech: 'C#, Python, WebAPI',
            github: '',
            website: ''
        }
    ];
}

function renderCards(data) {
    const cardContainer = document.getElementsByClassName('projects-container')[0];

    data.forEach((card) => {
        const cardElement = document.createElement('div');
        cardElement.classList.add('card');
        cardElement.innerHTML = `
            <h2>${card.projectName}</h2>
            <p>${card.description}</p>
            <p id="tech">Status: <b>${card.status}</b><br>Tech: <b>${card.tech}</b></p>
            <p id="det"> click to see details </p>
        `;
        cardElement.onclick = function () {
            animate_expanded_card();
            load_expanded_content(card);
        };
        cardContainer.appendChild(cardElement);
    });
}

renderCards(cardsData);



function animate_expanded_card() {
    const expandedCard = document.getElementById("expanded-card");
    let delay = 700;
    expandedCard.style.visibility = "visible";        
    anime({
        targets: '#expanded-card',
        scale: [0,1],
        opacity: [0,1],
        easing: "easeOutQuad",
        duration: delay
    });
}

function load_expanded_content(card) {
    console.log(card.projectName + ' ' + card.status);
    
    const expandedCard = document.getElementById("expanded-card");
    expandedCard.innerHTML = `
        <h1 onclick="close_expand()"></h1>
        <h2>${card.projectName}</h2>
        <p>${card.details}</p>
        <img src="${card.img[0]}">
    `;
}

function close_expand() {
    const expandedCard = document.getElementById("expanded-card");
    let delay = 700;
    expandedCard.style.transition = "cubic-bezier(0, 2.28, 0.95, 0.69) 5s";
    expandedCard.style.webkitTransition = "cubic-bezier(0, 2.28, 0.95, 0.69) 5s";
    expandedCard.style.visibility = "hidden";
    anime({
        targets: '#expanded-card',
        scale: [1,0],
        opacity: [1,0],
        easing: "easeOutQuad",
        duration: delay
    });
    setTimeout(() => {
        expandedCard.style.transition = "cubic-bezier(0, 2.28, 0.95, 0.69) 0.7s";
        expandedCard.style.webkitTransition = "cubic-bezier(0, 2.28, 0.95, 0.69) 0.7s";
    }, delay);
}